### ISSUE TITLE
【Issueではなく】【お問い合わせ】950A10220003900001_01.xmlの作成の仕方

### ISSUE THREAD

**Issue by tquangdo** [itaruMatumoto/eGovSignedXmlCreationEnvironment#1]
お世話になります。
ご連携ありがとうございます。とても助かります。
掲題の件、下記XMLの作成の仕方について伺いたいと思います。
https://github.com/itaruMatumoto/eGovSignedXmlCreationEnvironment/blob/master/zip_data/indivisual/in/950A102200039000(1)/950A10220003900001_01.xml

- ”950A102200039000**02**_01.xml”のFMTは下記のように、ネットで検索できますが。。。
https://developer.e-gov.go.jp/contents/specification/document-api/social-insurance.html

- ”950A102200039000**01**_01.xml”のFMTはどこで取得できるかまだわかっていない。”<P1_”と”<P2_”の作成の仕方がわかっていないから

### ★★質問の背景

- Githubのように、"950A102810040000"の手続ID（**労働**保険関係手続）も申請APIを実装したいですが、”950A102810040000**01**_01.xml”の作成の仕方がわかっていない
> ”950A102810040000**02**_01.xml”のFMTは下記のように、[ネット](https://developer.e-gov.go.jp/contents/specification/document-api/labor-insurance.html)で検索できますが。。。

ご返信、お待ちしております。
よろしくお願いします。

**Comment by itaruMatumoto** [comment]
質問者様

松本です。お世話になっております。
950A10220003900001_01.xml作成の件です。

eGovサイトから雛型XMLをダウンロードして、
テキストエディタを使って手入力しました。
その際、以下２点について、申請書XML仕様を
事前に調べた上で作業しました。
・必須項目については、必ず指定する
・文字種別及び文字数については、仕様書の指示に合わせる

実際に作業をしたところ、２～３回エラーがありました。
その都度、e-Govレスポンスのエラー内容を確認して、
XMLを修正しました。
エラー内容については、BASE64でエンコードされているので、
そのままでは見えません。以下のサイトでデコードしてから
ブラウザで表示しました。
https://hogehoge.tk/tool/

以上、参考にして頂けたらと思います。
